package com.aivle.backend.audit;

public enum AuditEventType {
    USER_SIGNED_UP,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    REFRESH_ROTATED,
    LOGOUT_COMPLETED,
    MISSING_FIELD_FILLED,
    MISSING_FIELD_WAIVED,
    STRUCTURED_PLAN_CONFIRMED,
    LEGAL_REVIEW_REQUESTED,
    LEGAL_REVIEW_COMPLETED,
    LEGAL_REVIEW_FAILED,
    FEASIBILITY_ANALYSIS_REQUESTED,
    FEASIBILITY_ANALYSIS_COMPLETED,
    FEASIBILITY_ANALYSIS_FAILED,
    PERSONA_RECOMMENDATION_REQUESTED,
    PERSONA_RECOMMENDATION_COMPLETED,
    PERSONA_RECOMMENDATION_FAILED
}
