package com.aivle.backend.taskrun.domain;
public enum TaskType { IDEA_INTERPRETATION, IDEA_ATTACHMENT_PARSE, IDEA_CONVERSATION_TURN, LEGAL_REVIEW, IDEA_LEGAL_PRECHECK, CONCEPT_LEGAL_VALIDATION, CONCEPT_GENERATION, QUICK_ASSESSMENT, DETAILED_ANALYSIS, PERSONA_CARD_GENERATION, PERSONA_INTERVIEW, INTERVIEW_SYNTHESIS, MARKETING_GENERATION, MARKETING_COMPARISON, FINAL_REPORT_GENERATION }
