import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Select, TextInput } from '../../../shared/ui/index.js';
import { useApiClient } from '../../../shared/api/ApiClientProvider.jsx';
import { createAdminApi } from '../api/adminApi.js';
import '../admin.css';

function useRemote(load, key) {
  const [state, setState] = useState({ loading: true, data: null, error: null });
  const [revision, setRevision] = useState(0);
  const refresh = useCallback(() => setRevision((current) => current + 1), []);
  // The caller supplies key as the explicit reload contract; load may be an inline request factory.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let active = true; Promise.resolve().then(load).then((data) => { if (active) setState({ loading: false, data, error: null }); }).catch((error) => { if (active) setState({ loading: false, data: null, error }); }); return () => { active = false; }; }, [key, revision]);
  return { ...state, refresh };
}
function PageHeader({ title, children }) { return <header className="admin-page-header"><h1>{title}</h1>{children && <p>{children}</p>}</header>; }
function Failure({ error, retry }) { return <div className="admin-panel admin-error">{error?.message || '데이터를 불러오지 못했습니다.'} <Button size="small" variant="outline" onClick={retry}>다시 시도</Button></div>; }
function Metric({ label, value }) { return <div className="admin-metric"><span>{label}</span><strong>{value ?? '—'}</strong></div>; }
function Status({ value }) { return <span className={`admin-status admin-status--${String(value || '').toLowerCase()}`}>{value || '—'}</span>; }

export function AdminOverviewPage() {
  const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const { data, loading, error, refresh } = useRemote(api.overview, api);
  if (loading) return <div className="admin-page"><PageHeader title="Overview">운영 지표를 불러오는 중입니다.</PageHeader></div>;
  if (error) return <div className="admin-page"><PageHeader title="Overview" /><Failure error={error} retry={refresh} /></div>;
  return <div className="admin-page"><PageHeader title="Overview">현재 운영 상태와 즉시 확인이 필요한 항목을 보여줍니다.</PageHeader><section className="admin-metrics" aria-label="운영 지표"><Metric label="전체 사용자" value={data.users.total} /><Metric label="활성 사용자" value={data.users.active} /><Metric label="잠긴 계정" value={data.users.locked} /><Metric label="전체 프로젝트" value={data.projects.total} /><Metric label="실패 작업" value={data.jobs.failed} /><Metric label="AI 작업" value={data.jobs.available ? data.jobs.running : '미연동'} /></section><section className="admin-panel"><h2>AI 서비스</h2><p>{data.jobs.available ? '작업 상태를 확인할 수 있습니다.' : 'AI 서버 미연동 — 현재 수집하지 않는 지표입니다.'}</p></section></div>;
}

function UserSheet({ user, onClose, onChanged }) {
  const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function action(type, value) { if (!reason.trim()) { setError('변경 사유를 입력하세요.'); return; } setBusy(true); setError(''); try { if (type === 'status') await api.updateStatus(user.id, { status: value, reason }); else if (type === 'role') await api.updateRole(user.id, { role: value, reason }); else await api.revokeSessions(user.id, { reason }); onChanged(); } catch (e) { setError(e.message || '작업에 실패했습니다.'); } finally { setBusy(false); } }
  return <aside className="admin-sheet" aria-label="사용자 상세"><header className="admin-sheet__header"><div><h2>{user.displayName || user.username}</h2><span>@{user.username}</span></div><Button size="small" variant="ghost" onClick={onClose}>닫기</Button></header><dl><dt>이메일</dt><dd>{user.email || '미등록'}</dd><dt>역할</dt><dd><Status value={user.role} /></dd><dt>계정 상태</dt><dd><Status value={user.accountStatus} /></dd><dt>프로젝트</dt><dd>{user.projectCount}</dd><dt>최근 로그인</dt><dd>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : '없음'}</dd></dl><TextInput label="변경 사유" value={reason} onChange={(e) => setReason(e.target.value)} required /><div className="admin-actions"><Button size="small" variant="outline" disabled={busy || user.accountStatus === 'LOCKED'} onClick={() => action('status', 'LOCKED')}>계정 잠금</Button><Button size="small" variant="outline" disabled={busy || user.accountStatus !== 'LOCKED'} onClick={() => action('status', 'ACTIVE')}>잠금 해제</Button><Button size="small" variant="outline" disabled={busy || user.accountStatus === 'DISABLED'} onClick={() => action('status', 'DISABLED')}>비활성화</Button><Button size="small" variant="outline" disabled={busy || user.accountStatus === 'ACTIVE'} onClick={() => action('status', 'ACTIVE')}>활성화</Button><Button size="small" variant="outline" disabled={busy || user.role === 'ADMIN'} onClick={() => action('role', 'ADMIN')}>ADMIN 승격</Button><Button size="small" variant="outline" disabled={busy || user.role === 'USER'} onClick={() => action('role', 'USER')}>USER 강등</Button><Button size="small" variant="outline" disabled={busy} onClick={() => action('revoke')}>모든 세션 종료</Button></div>{error && <p className="admin-error">{error}</p>}<p>위험 작업은 사유와 함께 기록되며, 역할·상태 변경 시 기존 세션이 철회됩니다.</p></aside>;
}

export function AdminUsersPage() {
  const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const [filters, setFilters] = useState({ keyword: '', role: '', status: '', page: 0, size: 20 }); const [selected, setSelected] = useState(null);
  const { data, loading, error, refresh } = useRemote(() => api.users(filters), filters);
  const choose = async (id) => { try { setSelected(await api.user(id)); } catch { setSelected(null); } };
  const update = (field, value) => setFilters((current) => ({ ...current, [field]: value, page: field === 'page' ? value : 0 }));
  return <div className="admin-page"><PageHeader title="Users">계정, 역할, 상태를 서버 권한으로 관리합니다.</PageHeader><section className="admin-panel"><div className="admin-toolbar"><TextInput label="검색" value={filters.keyword} placeholder="사용자명, 이메일, 이름" onChange={(e) => update('keyword', e.target.value)} /><Select label="Role" value={filters.role} onChange={(e) => update('role', e.target.value)}><option value="">전체</option><option value="USER">USER</option><option value="ADMIN">ADMIN</option></Select><Select label="상태" value={filters.status} onChange={(e) => update('status', e.target.value)}><option value="">전체</option><option value="ACTIVE">활성</option><option value="LOCKED">잠김</option><option value="DISABLED">비활성</option></Select></div>{loading ? <p>불러오는 중…</p> : error ? <Failure error={error} retry={refresh} /> : <><table className="admin-table"><caption className="visually-hidden">사용자 목록</caption><thead><tr><th>사용자</th><th>이메일</th><th>Role</th><th>상태</th><th>프로젝트</th><th>최근 로그인</th></tr></thead><tbody>{data.content.map((user) => <tr key={user.id} data-clickable="true" tabIndex="0" onClick={() => choose(user.id)} onKeyDown={(e) => { if (e.key === 'Enter') choose(user.id); }}><td>{user.displayName || user.username}<br /><small>@{user.username}</small></td><td>{user.email || '—'}</td><td><Status value={user.role} /></td><td><Status value={user.accountStatus} /></td><td>{user.projectCount}</td><td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table>{data.content.length === 0 && <p className="admin-empty">조건에 맞는 사용자가 없습니다.</p>}<div className="admin-pagination"><Button size="small" variant="outline" disabled={data.first} onClick={() => update('page', filters.page - 1)}>이전</Button><span>{data.number + 1} / {Math.max(data.totalPages, 1)}</span><Button size="small" variant="outline" disabled={data.last} onClick={() => update('page', filters.page + 1)}>다음</Button></div></>}</section>{selected && <UserSheet user={selected} onClose={() => setSelected(null)} onChanged={() => { setSelected(null); refresh(); }} />}</div>;
}

export function AdminProjectsPage() { const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const { data, loading, error, refresh } = useRemote(() => api.projects({ page: 0, size: 50 }), api); return <div className="admin-page"><PageHeader title="Projects">모든 프로젝트의 운영 현황만 조회합니다.</PageHeader><section className="admin-panel">{loading ? <p>불러오는 중…</p> : error ? <Failure error={error} retry={refresh} /> : <table className="admin-table"><thead><tr><th>프로젝트</th><th>소유자</th><th>Area</th><th>상태</th><th>단계</th><th>생성일</th></tr></thead><tbody>{data.content.map((p) => <tr key={p.id}><td>{p.title}</td><td>{p.ownerUsername}</td><td>{p.area || '—'}</td><td><Status value={p.status} /></td><td>{p.stage}</td><td>{new Date(p.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>}</section></div>; }

export function AdminAuditPage() { const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const { data, loading, error, refresh } = useRemote(() => api.audit({ page: 0, size: 50 }), api); return <div className="admin-page"><PageHeader title="Audit">관리자 변경은 사유, 변경 전후 값, 요청 ID와 함께 보존됩니다.</PageHeader><section className="admin-panel">{loading ? <p>불러오는 중…</p> : error ? <Failure error={error} retry={refresh} /> : <table className="admin-table"><thead><tr><th>시각</th><th>액션</th><th>대상</th><th>요청 ID</th><th>메타데이터</th></tr></thead><tbody>{data.content.map((event) => <tr key={event.id}><td>{new Date(event.occurredAt).toLocaleString()}</td><td>{event.action}</td><td>{event.aggregateType} #{event.aggregateId || '—'}</td><td>{event.requestId || '—'}</td><td>{event.metadata || '—'}</td></tr>)}</tbody></table>}</section></div>; }

export function AdminSettingsPage() { const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const { data, loading, error, refresh } = useRemote(api.settings, api); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(''); async function save(setting, value) { if (!reason.trim()) return; setSaving(setting.key); try { await api.updateSetting(setting.key, { value: String(value), reason }); refresh(); } finally { setSaving(''); } } return <div className="admin-page"><PageHeader title="Settings">지원되는 서비스 설정과 기능 플래그만 변경할 수 있습니다.</PageHeader><section className="admin-panel"><TextInput label="변경 사유" value={reason} onChange={(e) => setReason(e.target.value)} required />{loading ? <p>불러오는 중…</p> : error ? <Failure error={error} retry={refresh} /> : data.map((setting) => <div key={setting.key} className="admin-actions" style={{ marginTop: '1rem', justifyContent: 'space-between' }}><span><strong>{setting.key}</strong><br /><small>현재 값: {setting.value}</small></span><Button size="small" loading={saving === setting.key} disabled={!reason.trim()} onClick={() => save(setting, setting.value !== 'true')}>{setting.value === 'true' ? '비활성화' : '활성화'}</Button></div>)}</section></div>; }

export function AdminOperationsPage() { const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const { data, loading } = useRemote(api.services, api); return <div className="admin-page"><PageHeader title="Operations">백엔드, 데이터베이스, AI 연동 상태를 확인합니다.</PageHeader><section className="admin-panel"><h2>AI Service Registry</h2><p>{loading ? '상태 확인 중…' : data.available ? 'AI 서비스가 연결되었습니다.' : 'AI 서버 미연동 — 연동 준비 중입니다.'}</p></section></div>; }
export function AdminJobsPage() { const client = useApiClient(); const api = useMemo(() => createAdminApi(client), [client]); const { data, loading } = useRemote(api.jobs, api); return <div className="admin-page"><PageHeader title="AI Jobs">AI 서버가 연결되면 대기·실행·실패·재시도 상태가 표시됩니다.</PageHeader><section className="admin-panel"><p>{loading ? '작업 상태 확인 중…' : data.available ? '작업 목록을 불러왔습니다.' : 'AI 작업 관리가 아직 연결되지 않았습니다. Mock 작업 데이터는 표시하지 않습니다.'}</p></section></div>; }
