CREATE TABLE admin_action_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    purpose VARCHAR(60) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    security_version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_admin_action_token_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);
CREATE INDEX idx_admin_action_token_actor ON admin_action_tokens(actor_user_id, purpose, expires_at);
