CREATE TABLE cluster_persona_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baseline_persona_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL,
    updated_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_cluster_persona_policy_persona UNIQUE (baseline_persona_id),
    CONSTRAINT fk_cluster_persona_policy_persona
        FOREIGN KEY (baseline_persona_id) REFERENCES baseline_personas(id),
    CONSTRAINT fk_cluster_persona_policy_updater
        FOREIGN KEY (updated_by_user_id) REFERENCES users(id),
    CONSTRAINT ck_cluster_persona_policy_order CHECK (display_order > 0)
);

CREATE INDEX idx_cluster_persona_policy_visible_order
    ON cluster_persona_policies(enabled, display_order);

CREATE TABLE project_persona_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    baseline_persona_id BIGINT NOT NULL,
    selected_by_user_id BIGINT NOT NULL,
    selected_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_project_persona_selection_project UNIQUE (project_id),
    CONSTRAINT fk_project_persona_selection_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_project_persona_selection_persona
        FOREIGN KEY (baseline_persona_id) REFERENCES baseline_personas(id),
    CONSTRAINT fk_project_persona_selection_user
        FOREIGN KEY (selected_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_project_persona_selection_persona
    ON project_persona_selections(baseline_persona_id);
