CREATE TABLE marketing_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    purpose VARCHAR(40) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    format VARCHAR(40) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    selected_persona_id BIGINT,
    recommended_persona_code VARCHAR(100),
    source_snapshot_json TEXT NOT NULL,
    current_version INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_marketing_content_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_marketing_content_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_marketing_content_persona
        FOREIGN KEY (selected_persona_id) REFERENCES baseline_personas(id),
    CONSTRAINT ck_marketing_content_width CHECK (width BETWEEN 320 AND 4096),
    CONSTRAINT ck_marketing_content_height CHECK (height BETWEEN 320 AND 4096),
    CONSTRAINT ck_marketing_content_current_version CHECK (current_version > 0)
);

CREATE INDEX idx_marketing_content_project_updated
    ON marketing_contents(project_id, deleted_at, updated_at);

CREATE TABLE marketing_content_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketing_content_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    headline VARCHAR(160) NOT NULL,
    subheadline VARCHAR(240),
    body_copy TEXT,
    call_to_action VARCHAR(80),
    supporting_text VARCHAR(240),
    visual_style VARCHAR(30) NOT NULL,
    color_theme VARCHAR(30) NOT NULL,
    layout_template VARCHAR(30) NOT NULL,
    background_type VARCHAR(30) NOT NULL,
    background_value VARCHAR(500),
    accent_color VARCHAR(20),
    text_color VARCHAR(20),
    text_alignment VARCHAR(20) NOT NULL,
    headline_size INTEGER NOT NULL,
    show_cta BOOLEAN NOT NULL,
    show_persona_tag BOOLEAN NOT NULL,
    content_json TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_marketing_content_version
        UNIQUE (marketing_content_id, version_number),
    CONSTRAINT fk_marketing_content_version_content
        FOREIGN KEY (marketing_content_id) REFERENCES marketing_contents(id),
    CONSTRAINT fk_marketing_content_version_creator
        FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_marketing_content_version_content
    ON marketing_content_versions(marketing_content_id, version_number);
