CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, name VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP, last_login_at TIMESTAMP, password_changed_at TIMESTAMP, email_verified_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL, description TEXT, industry_category VARCHAR(100),
    stage VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);
CREATE INDEX idx_project_owner_status ON projects(owner_id, status);

CREATE TABLE product_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL, category VARCHAR(100), target_price DECIMAL(19,2), target_audience VARCHAR(255),
    summary TEXT, currency VARCHAR(3), features_json TEXT, value_proposition TEXT, active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, storage_type VARCHAR(30) NOT NULL,
    storage_key VARCHAR(500) NOT NULL UNIQUE, original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL, extension VARCHAR(20) NOT NULL, mime_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL, checksum_sha256 VARCHAR(64) NOT NULL, status VARCHAR(30) NOT NULL,
    encrypted BOOLEAN NOT NULL, retention_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE project_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    document_type VARCHAR(30) NOT NULL, current_version INTEGER NOT NULL, status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_document_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, stored_file_id BIGINT NOT NULL UNIQUE, parse_status VARCHAR(30) NOT NULL,
    uploaded_by BIGINT NOT NULL, uploaded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_document_version UNIQUE(document_id, version_number),
    CONSTRAINT fk_version_document FOREIGN KEY (document_id) REFERENCES project_documents(id),
    CONSTRAINT fk_version_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id),
    CONSTRAINT fk_version_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE structured_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    source_document_version_id BIGINT NOT NULL, version_number INTEGER NOT NULL, status VARCHAR(30) NOT NULL,
    completion_rate INTEGER NOT NULL CHECK (completion_rate BETWEEN 0 AND 100), raw_extracted_json TEXT,
    confirmed_by_user BOOLEAN NOT NULL, confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_plan_version UNIQUE(project_id, version_number),
    CONSTRAINT fk_plan_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_plan_source FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id)
);

CREATE TABLE structured_plan_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, structured_plan_id BIGINT NOT NULL,
    section_type VARCHAR(40) NOT NULL, title VARCHAR(150) NOT NULL, content_json TEXT, source_text TEXT,
    confidence DECIMAL(5,4), created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_section_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id)
);

CREATE TABLE missing_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, structured_plan_id BIGINT NOT NULL,
    field_code VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, required BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL, user_value_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_missing_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id)
);

CREATE TABLE analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    job_type VARCHAR(40) NOT NULL, status VARCHAR(30) NOT NULL, progress INTEGER NOT NULL DEFAULT 0,
    current_step VARCHAR(200), request_json TEXT, external_request_id VARCHAR(100),
    result_reference_type VARCHAR(50), result_reference_id BIGINT, error_code VARCHAR(100),
    error_message VARCHAR(500), retry_count INTEGER NOT NULL DEFAULT 0, started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_job_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT fk_job_project FOREIGN KEY (project_id) REFERENCES projects(id)
);
CREATE INDEX idx_job_project_type_status ON analysis_jobs(project_id, job_type, status);

CREATE TABLE legal_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE, status VARCHAR(30) NOT NULL, decision VARCHAR(30),
    risk_level VARCHAR(20), summary TEXT, model_version VARCHAR(100), knowledge_base_version VARCHAR(100),
    raw_result_json TEXT, started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_legal_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_legal_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id)
);

CREATE TABLE legal_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legal_review_id BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL, severity VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL,
    description TEXT, legal_basis TEXT, source_name VARCHAR(255), source_url TEXT, recommendation TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_finding_review FOREIGN KEY (legal_review_id) REFERENCES legal_reviews(id)
);

CREATE TABLE feasibility_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE, analysis_type VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL,
    score DECIMAL(5,2), decision VARCHAR(30), summary TEXT, input_snapshot_json TEXT, raw_result_json TEXT,
    model_version VARCHAR(100), started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_feasibility_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id)
);

CREATE TABLE analysis_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feasibility_analysis_id BIGINT NOT NULL,
    metric_key VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, numeric_value DECIMAL(19,4),
    text_value TEXT, unit VARCHAR(50), display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_metric_analysis FOREIGN KEY (feasibility_analysis_id) REFERENCES feasibility_analyses(id)
);

CREATE TABLE analysis_evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feasibility_analysis_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL, title VARCHAR(250) NOT NULL, source_url TEXT, summary TEXT, retrieved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_evidence_analysis FOREIGN KEY (feasibility_analysis_id) REFERENCES feasibility_analyses(id)
);

CREATE TABLE analysis_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feasibility_analysis_id BIGINT NOT NULL,
    priority VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT, display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_recommendation_analysis FOREIGN KEY (feasibility_analysis_id) REFERENCES feasibility_analyses(id)
);

CREATE TABLE financial_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE, status VARCHAR(30) NOT NULL, currency VARCHAR(3) NOT NULL,
    analysis_period_months INTEGER, expected_revenue DECIMAL(19,2), expected_cost DECIMAL(19,2),
    break_even_point_months INTEGER, roi DECIMAL(10,4), npv DECIMAL(19,2), irr DECIMAL(10,4),
    summary TEXT, assumptions_json TEXT, result_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_financial_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_financial_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id)
);
