CREATE TABLE ai_task_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL,
    ai_task_result_id BIGINT,
    stored_file_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_task_artifact_job_role
        UNIQUE (analysis_job_id, role),
    CONSTRAINT uk_ai_task_artifact_file UNIQUE (stored_file_id),
    CONSTRAINT fk_ai_task_artifact_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_ai_task_artifact_job
        FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id),
    CONSTRAINT fk_ai_task_artifact_result
        FOREIGN KEY (ai_task_result_id) REFERENCES ai_task_results(id),
    CONSTRAINT fk_ai_task_artifact_file
        FOREIGN KEY (stored_file_id) REFERENCES stored_files(id)
);

CREATE INDEX idx_ai_task_artifact_project
    ON ai_task_artifacts(project_id);
CREATE INDEX idx_ai_task_artifact_job
    ON ai_task_artifacts(analysis_job_id);
CREATE INDEX idx_ai_task_artifact_result
    ON ai_task_artifacts(ai_task_result_id);
