CREATE TABLE idea_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_type VARCHAR(10) NOT NULL,
    title VARCHAR(200),
    original_text TEXT NOT NULL,
    original_file_reference VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_sources_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT ck_idea_sources_type CHECK (source_type IN ('TEXT', 'FILE'))
);

CREATE TABLE idea_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    normalized_description TEXT NOT NULL,
    facts_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    constraints_json TEXT NOT NULL,
    open_questions_json TEXT NOT NULL,
    readiness VARCHAR(30) NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_versions_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_idea_versions_source FOREIGN KEY (source_id) REFERENCES idea_sources(id),
    CONSTRAINT uk_idea_versions_number UNIQUE (project_id, version_number),
    CONSTRAINT ck_idea_versions_readiness CHECK (readiness IN ('UNDER_SPECIFIED', 'APPROPRIATE', 'OVER_SPECIFIED'))
);

CREATE TABLE idea_interpretation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL,
    result_json TEXT,
    error VARCHAR(100),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_interpretation_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_idea_interpretation_source FOREIGN KEY (source_id) REFERENCES idea_sources(id),
    CONSTRAINT fk_idea_interpretation_task_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE legal_review_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    idea_version_id BIGINT NOT NULL,
    task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL,
    legal_status VARCHAR(40),
    result_json TEXT,
    source_verified BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_review_runs_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_legal_review_runs_idea_version FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_legal_review_runs_task_run FOREIGN KEY (task_run_id) REFERENCES task_runs(id),
    CONSTRAINT ck_legal_review_source_unverified CHECK (source_verified = FALSE)
);

CREATE INDEX idx_idea_sources_current ON idea_sources(project_id, created_at DESC, id DESC);
CREATE INDEX idx_idea_versions_current ON idea_versions(project_id, version_number DESC);
CREATE INDEX idx_idea_interpretation_current ON idea_interpretation_runs(project_id, created_at DESC, id DESC);
CREATE INDEX idx_legal_review_current ON legal_review_runs(project_id, created_at DESC, id DESC);
