CREATE TABLE concept_generation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_generation_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_concept_generation_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_concept_generation_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, generation_run_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concepts_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_concepts_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_concepts_generation FOREIGN KEY (generation_run_id) REFERENCES concept_generation_runs(id),
    CONSTRAINT uk_concepts_generation_order UNIQUE (generation_run_id, display_order)
);

CREATE TABLE concept_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, name VARCHAR(200) NOT NULL, one_line_summary TEXT NOT NULL,
    target_customer TEXT NOT NULL, problem TEXT NOT NULL, solution TEXT NOT NULL,
    value_proposition TEXT NOT NULL, revenue_model TEXT NOT NULL,
    key_features_json TEXT NOT NULL, differentiators_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL, risks_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_versions_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_concept_versions_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_concept_versions_concept FOREIGN KEY (concept_id) REFERENCES concepts(id),
    CONSTRAINT uk_concept_versions_number UNIQUE (concept_id, version_number)
);

CREATE TABLE quick_assessment_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_quick_runs_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_quick_runs_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_quick_runs_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE quick_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, run_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL,
    market_score INTEGER NOT NULL, customer_value_score INTEGER NOT NULL, feasibility_score INTEGER NOT NULL,
    differentiation_score INTEGER NOT NULL, revenue_potential_score INTEGER NOT NULL, legal_risk_score INTEGER NOT NULL,
    overall_score DECIMAL(5,2) NOT NULL, summary TEXT NOT NULL, strengths_json TEXT NOT NULL, weaknesses_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_quick_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_quick_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_quick_run FOREIGN KEY (run_id) REFERENCES quick_assessment_runs(id),
    CONSTRAINT fk_quick_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT uk_quick_run_concept UNIQUE (run_id, concept_version_id)
);

CREATE TABLE shortlist_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL,
    selected_concept_version_ids_json TEXT NOT NULL, reason TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_shortlist_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_shortlist_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id)
);

CREATE TABLE detailed_analysis_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, task_run_id VARCHAR(64),
    state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_detailed_runs_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_detailed_runs_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_detailed_runs_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE detailed_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, run_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL,
    market_analysis TEXT NOT NULL, customer_analysis TEXT NOT NULL, business_model_analysis TEXT NOT NULL,
    operation_analysis TEXT NOT NULL, risk_analysis TEXT NOT NULL, recommendation TEXT NOT NULL,
    assumptions_json TEXT NOT NULL, research_needs_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_detailed_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_detailed_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_detailed_run FOREIGN KEY (run_id) REFERENCES detailed_analysis_runs(id),
    CONSTRAINT fk_detailed_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT uk_detailed_run_concept UNIQUE (run_id, concept_version_id)
);

ALTER TABLE financial_analyses ADD COLUMN journey_idea_version_id BIGINT;
ALTER TABLE financial_analyses ADD COLUMN journey_concept_version_id BIGINT;
ALTER TABLE financial_analyses ADD COLUMN unit_price DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN monthly_customers INTEGER;
ALTER TABLE financial_analyses ADD COLUMN variable_cost_per_customer DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN monthly_fixed_cost DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN initial_investment DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN monthly_revenue DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN monthly_variable_cost DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN monthly_total_cost DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN monthly_operating_profit DECIMAL(19,2);
ALTER TABLE financial_analyses ADD COLUMN break_even_customers INTEGER;
ALTER TABLE financial_analyses ADD COLUMN payback_months DECIMAL(10,2);
ALTER TABLE financial_analyses ADD CONSTRAINT fk_financial_journey_idea FOREIGN KEY (journey_idea_version_id) REFERENCES idea_versions(id);
ALTER TABLE financial_analyses ADD CONSTRAINT fk_financial_journey_concept FOREIGN KEY (journey_concept_version_id) REFERENCES concept_versions(id);
CREATE INDEX idx_financial_journey_concept ON financial_analyses(journey_concept_version_id) WHERE journey_concept_version_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE concept_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_selection_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_selection_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_selection_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id)
);

CREATE INDEX idx_concept_generation_current ON concept_generation_runs(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_concepts_current ON concepts(project_id, idea_version_id, display_order);
CREATE INDEX idx_quick_current ON quick_assessment_runs(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_shortlist_current ON shortlist_decisions(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_detailed_current ON detailed_analysis_runs(project_id, idea_version_id, created_at DESC, id DESC);
CREATE INDEX idx_selection_current ON concept_selections(project_id, idea_version_id, created_at DESC, id DESC);
