CREATE TABLE persona_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, segment_code VARCHAR(100) NOT NULL UNIQUE,
    segment_name VARCHAR(150) NOT NULL, age_group VARCHAR(50), gender VARCHAR(20), sample_count INTEGER,
    weighted_share DECIMAL(7,4), traits_json TEXT, source_dataset VARCHAR(200),
    cluster_model_version VARCHAR(100), active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE persona_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, segment_id BIGINT, owner_id BIGINT,
    name VARCHAR(100) NOT NULL, age INTEGER, gender VARCHAR(10), occupation VARCHAR(50),
    background TEXT, traits_json TEXT, is_system BOOLEAN NOT NULL, active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_segment FOREIGN KEY (segment_id) REFERENCES persona_segments(id),
    CONSTRAINT fk_persona_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE persona_prompt_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, persona_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, system_prompt TEXT NOT NULL, generation_model VARCHAR(100), parameters_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_persona_prompt_version UNIQUE(persona_id, version_number),
    CONSTRAINT fk_prompt_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id)
);

CREATE TABLE project_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL, persona_id BIGINT NOT NULL,
    weight DECIMAL(7,4), active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_project_persona UNIQUE(project_id, persona_id),
    CONSTRAINT fk_project_persona_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_project_persona_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id)
);

CREATE TABLE simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL, simulation_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL,
    total_rounds INTEGER, current_round INTEGER, progress INTEGER, configuration_json TEXT,
    started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_simulation_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE simulation_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL, persona_id BIGINT NOT NULL,
    role VARCHAR(50), weight DECIMAL(7,4), profile_snapshot_json TEXT, prompt_snapshot TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_simulation_persona UNIQUE(simulation_id, persona_id),
    CONSTRAINT fk_sim_persona_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id),
    CONSTRAINT fk_sim_persona_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id)
);

CREATE TABLE simulation_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL, status VARCHAR(30) NOT NULL, summary TEXT, started_at TIMESTAMP, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_simulation_round UNIQUE(simulation_id, round_number),
    CONSTRAINT fk_round_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id)
);

CREATE TABLE fgi_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL, question_type VARCHAR(20) NOT NULL, evaluation_axis VARCHAR(100),
    question_text TEXT NOT NULL, options_json TEXT, required BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_question_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id)
);

CREATE TABLE fgi_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL, persona_id BIGINT NOT NULL, answer_text TEXT, score DECIMAL(7,2),
    sentiment VARCHAR(20), keywords_json TEXT, follow_up BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_response_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id),
    CONSTRAINT fk_response_question FOREIGN KEY (question_id) REFERENCES fgi_questions(id),
    CONSTRAINT fk_response_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id)
);

CREATE TABLE discussion_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    persona_id BIGINT NOT NULL, round_id BIGINT, round_number INTEGER, turn_number INTEGER,
    content TEXT NOT NULL, room_group VARCHAR(50), sentiment VARCHAR(20), keywords_json TEXT, reply_to_log_id BIGINT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_log_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id),
    CONSTRAINT fk_log_persona FOREIGN KEY (persona_id) REFERENCES persona_instances(id),
    CONSTRAINT fk_log_round FOREIGN KEY (round_id) REFERENCES simulation_rounds(id),
    CONSTRAINT fk_log_reply FOREIGN KEY (reply_to_log_id) REFERENCES discussion_logs(id)
);

CREATE TABLE simulation_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    insight_type VARCHAR(100) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT,
    supporting_data_json TEXT, display_order INTEGER,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_insight_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id)
);

CREATE TABLE prediction_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, simulation_id BIGINT NOT NULL,
    metric_key VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, metric_value DECIMAL(19,4),
    unit VARCHAR(50), segment_breakdown_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_prediction_simulation FOREIGN KEY (simulation_id) REFERENCES simulations(id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    report_type VARCHAR(40) NOT NULL, title VARCHAR(150) NOT NULL, status VARCHAR(20) NOT NULL,
    current_version INTEGER NOT NULL, summary TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE report_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, content_json TEXT NOT NULL, generation_model VARCHAR(100), source_snapshot_json TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_report_version UNIQUE(report_id, version_number),
    CONSTRAINT fk_report_version_report FOREIGN KEY (report_id) REFERENCES reports(id)
);

CREATE TABLE report_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_version_id BIGINT NOT NULL,
    source_type VARCHAR(50) NOT NULL, source_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_source_version FOREIGN KEY (report_version_id) REFERENCES report_versions(id)
);

CREATE TABLE report_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_version_id BIGINT NOT NULL,
    stored_file_id BIGINT NOT NULL UNIQUE, file_format VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_file_version FOREIGN KEY (report_version_id) REFERENCES report_versions(id),
    CONSTRAINT fk_report_file_stored FOREIGN KEY (stored_file_id) REFERENCES stored_files(id)
);

CREATE TABLE marketing_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id BIGINT NOT NULL,
    product_service_id BIGINT, material_type VARCHAR(40) NOT NULL, title VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL, target_persona_segment_id BIGINT, prompt TEXT, content_json TEXT,
    representative_file_id BIGINT UNIQUE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_material_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_material_product FOREIGN KEY (product_service_id) REFERENCES product_services(id),
    CONSTRAINT fk_material_segment FOREIGN KEY (target_persona_segment_id) REFERENCES persona_segments(id),
    CONSTRAINT fk_material_file FOREIGN KEY (representative_file_id) REFERENCES stored_files(id)
);

CREATE TABLE marketing_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, marketing_material_id BIGINT NOT NULL,
    stored_file_id BIGINT NOT NULL UNIQUE, asset_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_asset_material FOREIGN KEY (marketing_material_id) REFERENCES marketing_materials(id),
    CONSTRAINT fk_asset_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id)
);

CREATE TABLE marketing_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, marketing_material_id BIGINT NOT NULL,
    variant_number INTEGER NOT NULL, content_json TEXT NOT NULL, stored_file_id BIGINT UNIQUE, score DECIMAL(5,2),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_marketing_variant UNIQUE(marketing_material_id, variant_number),
    CONSTRAINT fk_variant_material FOREIGN KEY (marketing_material_id) REFERENCES marketing_materials(id),
    CONSTRAINT fk_variant_file FOREIGN KEY (stored_file_id) REFERENCES stored_files(id)
);
