CREATE TABLE persona_studies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL,
    generation_task_run_id VARCHAR(64), state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100),
    synthetic_notice VARCHAR(300) NOT NULL, completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_study_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_persona_study_idea FOREIGN KEY (idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_persona_study_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_persona_study_task FOREIGN KEY (generation_task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE persona_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL, selected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_card_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_persona_card_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_persona_card_study FOREIGN KEY (study_id) REFERENCES persona_studies(id),
    CONSTRAINT uk_persona_card_order UNIQUE (study_id, display_order)
);

CREATE TABLE persona_card_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, persona_card_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL, name VARCHAR(200) NOT NULL, short_label VARCHAR(200) NOT NULL,
    role_and_context_json TEXT NOT NULL, problem_and_needs_json TEXT NOT NULL,
    behavior_and_decision_json TEXT NOT NULL, interview_focus_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_version_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_persona_version_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_persona_version_card FOREIGN KEY (persona_card_id) REFERENCES persona_cards(id),
    CONSTRAINT uk_persona_version_number UNIQUE (persona_card_id, version_number)
);

CREATE TABLE persona_interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL,
    persona_card_version_id BIGINT NOT NULL, task_run_id VARCHAR(64), state VARCHAR(20) NOT NULL,
    result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_persona_interview_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_persona_interview_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_persona_interview_study FOREIGN KEY (study_id) REFERENCES persona_studies(id),
    CONSTRAINT fk_persona_interview_card_version FOREIGN KEY (persona_card_version_id) REFERENCES persona_card_versions(id),
    CONSTRAINT fk_persona_interview_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE persona_interview_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, interview_id BIGINT NOT NULL,
    sequence_number INTEGER NOT NULL, category VARCHAR(40) NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_interview_message_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_interview_message_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_interview_message_interview FOREIGN KEY (interview_id) REFERENCES persona_interviews(id),
    CONSTRAINT uk_interview_message_sequence UNIQUE (interview_id, sequence_number)
);

CREATE TABLE interview_synthesis_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL,
    task_run_id VARCHAR(64), interview_ids_json TEXT NOT NULL, state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_synthesis_run_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_synthesis_run_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_synthesis_run_study FOREIGN KEY (study_id) REFERENCES persona_studies(id),
    CONSTRAINT fk_synthesis_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id)
);

CREATE TABLE interview_syntheses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, study_id BIGINT NOT NULL, run_id BIGINT NOT NULL,
    common_themes_json TEXT NOT NULL, conflicting_views_json TEXT NOT NULL, critical_needs_json TEXT NOT NULL,
    decision_barriers_json TEXT NOT NULL, implications_json TEXT NOT NULL, research_needs_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_synthesis_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_synthesis_concept FOREIGN KEY (concept_version_id) REFERENCES concept_versions(id),
    CONSTRAINT fk_synthesis_study FOREIGN KEY (study_id) REFERENCES persona_studies(id),
    CONSTRAINT fk_synthesis_run FOREIGN KEY (run_id) REFERENCES interview_synthesis_runs(id),
    CONSTRAINT uk_synthesis_run UNIQUE (run_id)
);

CREATE INDEX idx_persona_study_current ON persona_studies(project_id, concept_version_id, created_at DESC, id DESC);
CREATE INDEX idx_persona_cards_study ON persona_cards(study_id, display_order);
CREATE INDEX idx_persona_interviews_study ON persona_interviews(study_id, persona_card_version_id, created_at DESC, id DESC);
CREATE INDEX idx_synthesis_current ON interview_synthesis_runs(study_id, created_at DESC, id DESC);
