CREATE TABLE marketing_workspaces (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, synthesis_id BIGINT NOT NULL,
 state VARCHAR(20) NOT NULL, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_workspace_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_marketing_workspace_idea FOREIGN KEY(idea_version_id) REFERENCES idea_versions(id),
 CONSTRAINT fk_marketing_workspace_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_marketing_workspace_synthesis FOREIGN KEY(synthesis_id) REFERENCES interview_syntheses(id)
);
CREATE TABLE marketing_generation_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, task_run_id VARCHAR(64),
 state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_run_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_marketing_run_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_marketing_run_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id),
 CONSTRAINT fk_marketing_run_task FOREIGN KEY(task_run_id) REFERENCES task_runs(id)
);
CREATE TABLE journey_marketing_assets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, generation_run_id BIGINT NOT NULL,
 asset_type VARCHAR(30) NOT NULL, display_order INTEGER NOT NULL, selected BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_asset_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_marketing_asset_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_marketing_asset_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id),
 CONSTRAINT fk_marketing_asset_run FOREIGN KEY(generation_run_id) REFERENCES marketing_generation_runs(id),
 CONSTRAINT ck_marketing_asset_type CHECK(asset_type IN('POSITIONING','CORE_MESSAGE','SLOGAN','SOCIAL_COPY','LANDING_HERO','EMAIL_COPY','CHANNEL_PLAN'))
);
CREATE TABLE marketing_asset_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, asset_id BIGINT NOT NULL,
 version_number INTEGER NOT NULL, title VARCHAR(300) NOT NULL, content_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_version_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_marketing_version_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_marketing_version_asset FOREIGN KEY(asset_id) REFERENCES journey_marketing_assets(id),
 CONSTRAINT uk_marketing_version_number UNIQUE(asset_id,version_number)
);
CREATE TABLE marketing_comparison_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, task_run_id VARCHAR(64),
 asset_version_ids_json TEXT NOT NULL, state VARCHAR(20) NOT NULL, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_comparison_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_marketing_comparison_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_marketing_comparison_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id),
 CONSTRAINT fk_marketing_comparison_task FOREIGN KEY(task_run_id) REFERENCES task_runs(id)
);
CREATE TABLE marketing_comparisons (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL, run_id BIGINT NOT NULL,
 result_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_marketing_comparison_result_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_marketing_comparison_result_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_marketing_comparison_result_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id),
 CONSTRAINT fk_marketing_comparison_result_run FOREIGN KEY(run_id) REFERENCES marketing_comparison_runs(id),
 CONSTRAINT uk_marketing_comparison_result_run UNIQUE(run_id)
);
CREATE TABLE final_reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, idea_version_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, workspace_id BIGINT NOT NULL,
 task_run_id VARCHAR(64), source_reference_json TEXT NOT NULL, state VARCHAR(20) NOT NULL, ai_decision VARCHAR(30), user_decision VARCHAR(30),
 user_decision_reasons_json TEXT, result_json TEXT, error VARCHAR(100), completed_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_final_report_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_final_report_idea FOREIGN KEY(idea_version_id) REFERENCES idea_versions(id),
 CONSTRAINT fk_final_report_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_final_report_workspace FOREIGN KEY(workspace_id) REFERENCES marketing_workspaces(id),
 CONSTRAINT fk_final_report_task FOREIGN KEY(task_run_id) REFERENCES task_runs(id)
);
CREATE TABLE final_report_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL, concept_version_id BIGINT NOT NULL, report_id BIGINT NOT NULL,
 version_number INTEGER NOT NULL, content_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
 CONSTRAINT fk_final_report_version_project FOREIGN KEY(project_id) REFERENCES projects(id),
 CONSTRAINT fk_final_report_version_concept FOREIGN KEY(concept_version_id) REFERENCES concept_versions(id),
 CONSTRAINT fk_final_report_version_report FOREIGN KEY(report_id) REFERENCES final_reports(id),
 CONSTRAINT uk_final_report_version_number UNIQUE(report_id,version_number)
);
CREATE INDEX idx_marketing_workspace_current ON marketing_workspaces(project_id,concept_version_id,created_at DESC,id DESC);
CREATE INDEX idx_marketing_assets_workspace ON journey_marketing_assets(workspace_id,asset_type,display_order);
CREATE INDEX idx_marketing_comparison_current ON marketing_comparison_runs(workspace_id,created_at DESC,id DESC);
CREATE INDEX idx_final_report_current ON final_reports(project_id,concept_version_id,created_at DESC,id DESC);
