CREATE TABLE idea_origin_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    source_idea_version_id BIGINT NOT NULL,
    based_on_origin_version_id BIGINT,
    version_number INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    snapshot_json TEXT NOT NULL,
    confirmed_values_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    missing_fields_json TEXT NOT NULL,
    metadata_json TEXT NOT NULL,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_origin_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_idea_origin_source FOREIGN KEY (source_id) REFERENCES idea_sources(id),
    CONSTRAINT fk_idea_origin_source_version FOREIGN KEY (source_idea_version_id) REFERENCES idea_versions(id),
    CONSTRAINT fk_idea_origin_based_on FOREIGN KEY (based_on_origin_version_id) REFERENCES idea_origin_versions(id),
    CONSTRAINT uk_idea_origin_version UNIQUE (project_id, version_number),
    CONSTRAINT ck_idea_origin_state CHECK (state IN ('DRAFT', 'CONFIRMED'))
);

CREATE TABLE idea_clarification_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    origin_draft_version_id BIGINT NOT NULL,
    target_field VARCHAR(160) NOT NULL,
    requirement VARCHAR(40) NOT NULL,
    question TEXT NOT NULL,
    reason TEXT NOT NULL,
    answer TEXT,
    answer_source VARCHAR(300),
    status VARCHAR(30) NOT NULL,
    answered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_idea_clarification_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_idea_clarification_origin FOREIGN KEY (origin_draft_version_id) REFERENCES idea_origin_versions(id),
    CONSTRAINT ck_idea_clarification_requirement CHECK (requirement IN ('REQUIRED_FOR_IDEA_ORIGIN', 'REQUIRED_FOR_LEGAL_PRECHECK')),
    CONSTRAINT ck_idea_clarification_status CHECK (status IN ('MISSING', 'USER_CONFIRMED'))
);

CREATE INDEX idx_idea_origin_current ON idea_origin_versions(project_id, source_id, created_at DESC, id DESC);
CREATE INDEX idx_idea_origin_state ON idea_origin_versions(project_id, state, version_number DESC);
CREATE INDEX idx_idea_clarification_origin ON idea_clarification_questions(origin_draft_version_id, id);
