CREATE TABLE legal_precheck_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    idea_origin_version_id BIGINT NOT NULL,
    task_run_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    registry_version VARCHAR(40) NOT NULL,
    prompt_version VARCHAR(40) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_precheck_run_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_legal_precheck_run_origin FOREIGN KEY (idea_origin_version_id) REFERENCES idea_origin_versions(id),
    CONSTRAINT fk_legal_precheck_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id),
    CONSTRAINT uk_legal_precheck_run_task UNIQUE (task_run_id),
    CONSTRAINT ck_legal_precheck_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE TABLE legal_precheck_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    idea_origin_version_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    status VARCHAR(40) NOT NULL,
    source_status VARCHAR(30) NOT NULL,
    summary TEXT NOT NULL,
    findings_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    questions_json TEXT NOT NULL,
    revision_suggestions_json TEXT NOT NULL,
    concept_builder_allowed BOOLEAN NOT NULL,
    source_verified BOOLEAN NOT NULL,
    registry_version VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_precheck_version_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_legal_precheck_version_origin FOREIGN KEY (idea_origin_version_id) REFERENCES idea_origin_versions(id),
    CONSTRAINT fk_legal_precheck_version_run FOREIGN KEY (source_run_id) REFERENCES legal_precheck_runs(id),
    CONSTRAINT uk_legal_precheck_version_run UNIQUE (source_run_id),
    CONSTRAINT uk_legal_precheck_version_number UNIQUE (project_id, version_number),
    CONSTRAINT ck_legal_precheck_status CHECK (status IN ('PASS', 'PASS_WITH_CONDITIONS', 'REVISION_REQUIRED', 'PROHIBITED', 'INSUFFICIENT_INFORMATION', 'EXPERT_REVIEW_REQUIRED')),
    CONSTRAINT ck_legal_precheck_source_status CHECK (source_status IN ('SOURCE_COMPLETE', 'SOURCE_PARTIAL', 'REGISTRY_GAP'))
);

CREATE TABLE legal_guardrail_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    legal_precheck_version_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    hard_constraints_json TEXT NOT NULL,
    prohibited_patterns_json TEXT NOT NULL,
    conditional_constraints_json TEXT NOT NULL,
    required_disclosures_json TEXT NOT NULL,
    required_operational_controls_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_legal_guardrail_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_legal_guardrail_precheck FOREIGN KEY (legal_precheck_version_id) REFERENCES legal_precheck_versions(id),
    CONSTRAINT fk_legal_guardrail_run FOREIGN KEY (source_run_id) REFERENCES legal_precheck_runs(id),
    CONSTRAINT uk_legal_guardrail_precheck UNIQUE (legal_precheck_version_id),
    CONSTRAINT uk_legal_guardrail_version UNIQUE (project_id, version_number)
);

CREATE INDEX idx_legal_precheck_run_current ON legal_precheck_runs(project_id, created_at DESC, id DESC);
CREATE INDEX idx_legal_precheck_version_current ON legal_precheck_versions(project_id, version_number DESC);
CREATE INDEX idx_legal_guardrail_current ON legal_guardrail_sets(project_id, version_number DESC);
