CREATE TABLE concept_eligibility_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL, idea_origin_version_id BIGINT NOT NULL, legal_guardrail_set_id BIGINT NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL, prompt_version VARCHAR(40) NOT NULL, schema_version VARCHAR(20) NOT NULL,
    state VARCHAR(30) NOT NULL, current_round INTEGER NOT NULL, inspected_candidates INTEGER NOT NULL,
    eligible_candidates INTEGER NOT NULL, target_eligible_count INTEGER NOT NULL,
    max_replacement_rounds INTEGER NOT NULL, max_inspected_candidates INTEGER NOT NULL,
    needs_input_json TEXT NOT NULL, error_code VARCHAR(100), completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_batch_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_concept_batch_origin FOREIGN KEY (idea_origin_version_id) REFERENCES idea_origin_versions(id),
    CONSTRAINT fk_concept_batch_guardrail FOREIGN KEY (legal_guardrail_set_id) REFERENCES legal_guardrail_sets(id),
    CONSTRAINT ck_concept_batch_state CHECK (state IN ('GENERATING','VALIDATING_ORIGIN','VALIDATING_LEGAL','COMPLETED','NEEDS_INPUT','FAILED'))
);

CREATE TABLE concept_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, generation_task_run_id VARCHAR(64) NOT NULL,
    round_number INTEGER NOT NULL, sequence_number INTEGER NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL, prompt_version VARCHAR(40) NOT NULL, schema_version VARCHAR(20) NOT NULL,
    fingerprint VARCHAR(71) NOT NULL, draft_json TEXT NOT NULL,
    origin_status VARCHAR(20) NOT NULL, origin_reasons_json TEXT NOT NULL,
    legal_status VARCHAR(20), legal_reasons_json TEXT NOT NULL, violated_structure_keys_json TEXT NOT NULL,
    eligibility_status VARCHAR(20) NOT NULL, user_comment TEXT,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, deleted_at TIMESTAMP, version BIGINT NOT NULL,
    CONSTRAINT fk_concept_draft_batch FOREIGN KEY (batch_id) REFERENCES concept_eligibility_batches(id),
    CONSTRAINT fk_concept_draft_task FOREIGN KEY (generation_task_run_id) REFERENCES task_runs(id),
    CONSTRAINT uk_concept_draft_batch_sequence UNIQUE (batch_id, sequence_number),
    CONSTRAINT ck_concept_draft_origin CHECK (origin_status IN ('PASS','FAIL_ORIGIN')),
    CONSTRAINT ck_concept_draft_legal CHECK (legal_status IS NULL OR legal_status IN ('PASS','FAIL_LEGAL')),
    CONSTRAINT ck_concept_draft_eligibility CHECK (eligibility_status IN ('PENDING','ELIGIBLE','REJECTED'))
);

ALTER TABLE concept_versions ADD COLUMN eligibility_batch_id BIGINT;
ALTER TABLE concept_versions ADD COLUMN eligibility_status VARCHAR(20) NOT NULL DEFAULT 'LEGACY';
ALTER TABLE concept_versions ADD COLUMN target_segment_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE concept_versions ADD COLUMN positioning TEXT NOT NULL DEFAULT '';
ALTER TABLE concept_versions ADD COLUMN pricing_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE concept_versions ADD COLUMN channels_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE concept_versions ADD COLUMN operating_model_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE concept_versions ADD COLUMN new_business_activities_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE concept_versions ADD COLUMN origin_trace_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE concept_versions ADD COLUMN legal_trace_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE concept_versions ADD CONSTRAINT fk_concept_version_batch FOREIGN KEY (eligibility_batch_id) REFERENCES concept_eligibility_batches(id);
ALTER TABLE concept_versions ADD CONSTRAINT ck_concept_version_eligibility CHECK (eligibility_status IN ('LEGACY','ELIGIBLE'));

CREATE INDEX idx_concept_batch_current ON concept_eligibility_batches(project_id, created_at DESC, id DESC);
CREATE INDEX idx_concept_draft_batch ON concept_drafts(batch_id, sequence_number);
CREATE INDEX idx_concept_version_batch ON concept_versions(eligibility_batch_id, eligibility_status);
