ALTER TABLE concept_eligibility_batches
    ADD COLUMN retryable BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE concept_eligibility_batches
SET retryable = TRUE
WHERE state = 'FAILED'
  AND error_code IN (
      'AI_SERVICE_UNAVAILABLE', 'TASK_TIMEOUT', 'MODEL_DEPENDENCY_UNAVAILABLE',
      'REQUEST_DEADLINE_EXCEEDED', 'DEPENDENCY_UNAVAILABLE', 'RATE_LIMITED',
      'EXECUTION_FAILED', 'UNEXPECTED_INTERNAL_ERROR'
  );
