CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    token_jti VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_refresh_token_jti UNIQUE (token_jti),
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_refresh_token_user_revoked
    ON refresh_tokens(user_id, revoked_at);

CREATE INDEX idx_refresh_token_expires
    ON refresh_tokens(expires_at);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    project_id BIGINT,
    event_type VARCHAR(60) NOT NULL,
    aggregate_type VARCHAR(60),
    aggregate_id BIGINT,
    request_id VARCHAR(100),
    metadata_json TEXT,
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_project
        FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX idx_audit_actor_occurred
    ON audit_events(actor_user_id, occurred_at);

CREATE INDEX idx_audit_project_occurred
    ON audit_events(project_id, occurred_at);

CREATE INDEX idx_audit_event_occurred
    ON audit_events(event_type, occurred_at);

ALTER TABLE structured_plans
    ADD COLUMN confirmed_by_user_id BIGINT;

ALTER TABLE structured_plans
    ADD CONSTRAINT fk_plan_confirmed_by_user
    FOREIGN KEY (confirmed_by_user_id) REFERENCES users(id);

CREATE INDEX idx_plan_confirmed_by_user
    ON structured_plans(confirmed_by_user_id);
