ALTER TABLE analysis_jobs ADD COLUMN source_structured_plan_id BIGINT;
ALTER TABLE analysis_jobs ADD CONSTRAINT fk_job_source_structured_plan
    FOREIGN KEY (source_structured_plan_id) REFERENCES structured_plans(id);
CREATE INDEX idx_job_source_structured_plan ON analysis_jobs(source_structured_plan_id);

ALTER TABLE legal_reviews ADD COLUMN structured_plan_id BIGINT;
ALTER TABLE legal_reviews ADD COLUMN source_document_version_id BIGINT;
ALTER TABLE legal_reviews ADD COLUMN version_number INTEGER;
ALTER TABLE legal_reviews ADD COLUMN disclaimer TEXT;
ALTER TABLE legal_reviews ADD COLUMN provider VARCHAR(100);
ALTER TABLE legal_reviews ADD COLUMN model_name VARCHAR(100);
ALTER TABLE legal_reviews ADD COLUMN prompt_version VARCHAR(100);
ALTER TABLE legal_reviews ADD COLUMN prompt_hash VARCHAR(64);
ALTER TABLE legal_reviews ADD COLUMN raw_result_hash VARCHAR(64);
ALTER TABLE legal_reviews ADD COLUMN input_snapshot_json TEXT;
ALTER TABLE legal_reviews ADD CONSTRAINT fk_legal_review_plan
    FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id);
ALTER TABLE legal_reviews ADD CONSTRAINT fk_legal_review_source_version
    FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id);
ALTER TABLE legal_reviews ADD CONSTRAINT uk_legal_review_plan_prompt
    UNIQUE (structured_plan_id, prompt_version);
CREATE INDEX idx_legal_review_project_created ON legal_reviews(project_id, created_at);

ALTER TABLE legal_findings ADD COLUMN display_order INTEGER;
ALTER TABLE legal_findings ADD COLUMN applicability VARCHAR(40);
ALTER TABLE legal_findings ADD COLUMN rationale TEXT;
ALTER TABLE legal_findings ADD COLUMN evidence_json TEXT;
ALTER TABLE legal_findings ADD COLUMN source_section_codes_json TEXT;
ALTER TABLE legal_findings ADD COLUMN requires_professional_review BOOLEAN;
ALTER TABLE legal_findings ADD COLUMN confidence DECIMAL(5,4);
ALTER TABLE legal_findings ADD CONSTRAINT uk_legal_finding_review_category
    UNIQUE (legal_review_id, category);

CREATE TABLE legal_review_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_review_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    question TEXT NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_legal_question_review FOREIGN KEY (legal_review_id) REFERENCES legal_reviews(id),
    CONSTRAINT uk_legal_question_order UNIQUE (legal_review_id, display_order)
);
CREATE INDEX idx_legal_question_review ON legal_review_questions(legal_review_id);
