ALTER TABLE analysis_jobs ADD COLUMN source_legal_review_id BIGINT;
ALTER TABLE analysis_jobs ADD CONSTRAINT fk_job_source_legal_review
    FOREIGN KEY (source_legal_review_id) REFERENCES legal_reviews(id);
CREATE INDEX idx_job_source_legal_review ON analysis_jobs(source_legal_review_id);

CREATE TABLE feasibility_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE,
    structured_plan_id BIGINT NOT NULL,
    legal_review_id BIGINT NOT NULL,
    source_document_version_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    verdict VARCHAR(40) NOT NULL,
    overall_score INTEGER,
    confidence VARCHAR(20) NOT NULL,
    summary TEXT NOT NULL,
    key_strengths_json TEXT NOT NULL,
    key_risks_json TEXT NOT NULL,
    validation_tasks_summary_json TEXT NOT NULL,
    disclaimer TEXT NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(100) NOT NULL,
    catalog_version VARCHAR(100) NOT NULL,
    prompt_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    result_hash VARCHAR(64) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_assessment_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_feasibility_assessment_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id),
    CONSTRAINT fk_feasibility_assessment_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id),
    CONSTRAINT fk_feasibility_assessment_legal FOREIGN KEY (legal_review_id) REFERENCES legal_reviews(id),
    CONSTRAINT fk_feasibility_assessment_source FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id),
    CONSTRAINT ck_feasibility_overall_score CHECK (overall_score IS NULL OR overall_score BETWEEN 0 AND 100),
    CONSTRAINT uk_feasibility_assessment_input
        UNIQUE (structured_plan_id, legal_review_id, prompt_version, catalog_version)
);
CREATE INDEX idx_feasibility_assessment_project_created
    ON feasibility_assessments(project_id, created_at);

CREATE TABLE feasibility_dimension_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feasibility_assessment_id BIGINT NOT NULL,
    dimension_code VARCHAR(60) NOT NULL,
    display_order INTEGER NOT NULL,
    score INTEGER,
    confidence VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    finding TEXT NOT NULL,
    rationale TEXT NOT NULL,
    strengths_json TEXT NOT NULL,
    risks_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    source_section_codes_json TEXT NOT NULL,
    legal_finding_ids_json TEXT NOT NULL,
    recommended_actions_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_dimension_assessment
        FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id),
    CONSTRAINT ck_feasibility_dimension_score CHECK (score IS NULL OR score BETWEEN 0 AND 100),
    CONSTRAINT uk_feasibility_dimension UNIQUE (feasibility_assessment_id, dimension_code)
);
CREATE INDEX idx_feasibility_dimension_assessment
    ON feasibility_dimension_results(feasibility_assessment_id);

CREATE TABLE feasibility_validation_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feasibility_assessment_id BIGINT NOT NULL,
    task_code VARCHAR(100) NOT NULL,
    dimension_code VARCHAR(60) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    reason TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    validation_method TEXT NOT NULL,
    expected_evidence TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_feasibility_task_assessment
        FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id),
    CONSTRAINT uk_feasibility_task UNIQUE (feasibility_assessment_id, task_code)
);
CREATE INDEX idx_feasibility_task_assessment
    ON feasibility_validation_tasks(feasibility_assessment_id);
