ALTER TABLE analysis_jobs ADD COLUMN source_feasibility_assessment_id BIGINT;
ALTER TABLE analysis_jobs ADD CONSTRAINT fk_job_source_feasibility_assessment
    FOREIGN KEY (source_feasibility_assessment_id) REFERENCES feasibility_assessments(id);
CREATE INDEX idx_job_source_feasibility_assessment
    ON analysis_jobs(source_feasibility_assessment_id);

CREATE TABLE baseline_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_code VARCHAR(100) NOT NULL,
    cluster_id VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    short_name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    age_group VARCHAR(40) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    sample_size INTEGER,
    weighted_share DECIMAL(7,4),
    data_source VARCHAR(200) NOT NULL,
    data_version VARCHAR(100) NOT NULL,
    catalog_version VARCHAR(100) NOT NULL,
    key_traits_json TEXT NOT NULL,
    consumption_traits_json TEXT NOT NULL,
    technology_traits_json TEXT NOT NULL,
    channel_traits_json TEXT NOT NULL,
    subscription_traits_json TEXT NOT NULL,
    financial_traits_json TEXT NOT NULL,
    ai_usage_traits_json TEXT NOT NULL,
    demographic_summary_json TEXT NOT NULL,
    evidence_metrics_json TEXT NOT NULL,
    limitations_json TEXT NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_baseline_persona_code_catalog UNIQUE (persona_code, catalog_version),
    CONSTRAINT uk_baseline_persona_cluster_catalog UNIQUE (cluster_id, catalog_version),
    CONSTRAINT ck_baseline_persona_share
        CHECK (weighted_share IS NULL OR weighted_share BETWEEN 0 AND 1),
    CONSTRAINT ck_baseline_persona_sample
        CHECK (sample_size IS NULL OR sample_size >= 0)
);
CREATE INDEX idx_baseline_persona_catalog_order
    ON baseline_personas(catalog_version, display_order);

CREATE TABLE persona_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    analysis_job_id BIGINT NOT NULL UNIQUE,
    structured_plan_id BIGINT NOT NULL,
    feasibility_assessment_id BIGINT NOT NULL,
    source_document_version_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    primary_persona_code VARCHAR(100),
    secondary_persona_code VARCHAR(100),
    confidence VARCHAR(20) NOT NULL,
    summary TEXT NOT NULL,
    disclaimer TEXT NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(100) NOT NULL,
    catalog_version VARCHAR(100) NOT NULL,
    prompt_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    result_hash VARCHAR(64) NOT NULL,
    input_snapshot_json TEXT NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_recommendation_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_persona_recommendation_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id),
    CONSTRAINT fk_persona_recommendation_plan FOREIGN KEY (structured_plan_id) REFERENCES structured_plans(id),
    CONSTRAINT fk_persona_recommendation_feasibility
        FOREIGN KEY (feasibility_assessment_id) REFERENCES feasibility_assessments(id),
    CONSTRAINT fk_persona_recommendation_source
        FOREIGN KEY (source_document_version_id) REFERENCES document_versions(id),
    CONSTRAINT uk_persona_recommendation_input
        UNIQUE (structured_plan_id, feasibility_assessment_id, prompt_version, catalog_version)
);
CREATE INDEX idx_persona_recommendation_project_created
    ON persona_recommendations(project_id, created_at);

CREATE TABLE persona_recommendation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    baseline_persona_id BIGINT NOT NULL,
    recommendation_rank INTEGER NOT NULL,
    recommendation_level VARCHAR(40) NOT NULL,
    fit_score INTEGER,
    confidence VARCHAR(20) NOT NULL,
    match_reasons_json TEXT NOT NULL,
    mismatch_risks_json TEXT NOT NULL,
    assumptions_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    verification_questions_json TEXT NOT NULL,
    interpretation TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_item_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id),
    CONSTRAINT fk_persona_item_baseline
        FOREIGN KEY (baseline_persona_id) REFERENCES baseline_personas(id),
    CONSTRAINT uk_persona_item_persona UNIQUE (recommendation_id, baseline_persona_id),
    CONSTRAINT uk_persona_item_rank UNIQUE (recommendation_id, recommendation_rank),
    CONSTRAINT ck_persona_item_rank CHECK (recommendation_rank > 0),
    CONSTRAINT ck_persona_item_fit CHECK (fit_score IS NULL OR fit_score BETWEEN 0 AND 100)
);
CREATE INDEX idx_persona_item_recommendation
    ON persona_recommendation_items(recommendation_id);

CREATE TABLE customer_hypotheses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    persona_code VARCHAR(100) NOT NULL,
    hypothesis_type VARCHAR(40) NOT NULL,
    statement TEXT NOT NULL,
    rationale TEXT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_reference VARCHAR(200),
    confidence VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    validation_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_customer_hypothesis_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id)
);
CREATE INDEX idx_customer_hypothesis_recommendation
    ON customer_hypotheses(recommendation_id);

CREATE TABLE customer_validation_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    persona_code VARCHAR(100) NOT NULL,
    method VARCHAR(40) NOT NULL,
    objective TEXT NOT NULL,
    target_participant_description TEXT NOT NULL,
    suggested_sample_size INTEGER,
    recruitment_channel TEXT NOT NULL,
    success_criteria_json TEXT NOT NULL,
    expected_evidence_json TEXT NOT NULL,
    interview_questions_json TEXT NOT NULL,
    survey_questions_json TEXT NOT NULL,
    linked_feasibility_task_ids_json TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    disclaimer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_customer_validation_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id),
    CONSTRAINT uk_customer_validation_persona UNIQUE (recommendation_id, persona_code),
    CONSTRAINT ck_customer_validation_sample
        CHECK (suggested_sample_size IS NULL OR suggested_sample_size > 0)
);
CREATE INDEX idx_customer_validation_recommendation
    ON customer_validation_plans(recommendation_id);

CREATE TABLE persona_validation_task_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    feasibility_validation_task_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_persona_task_link_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES persona_recommendations(id),
    CONSTRAINT fk_persona_task_link_feasibility_task
        FOREIGN KEY (feasibility_validation_task_id) REFERENCES feasibility_validation_tasks(id),
    CONSTRAINT uk_persona_task_link
        UNIQUE (recommendation_id, feasibility_validation_task_id)
);
CREATE INDEX idx_persona_task_link_recommendation
    ON persona_validation_task_links(recommendation_id);
