spring:
  datasource:
    url: jdbc:h2:file:./data/aivle;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

app:
  ai-server:
    base-url: ${AI_SERVER_BASE_URL:http://127.0.0.1:8000}
