package com.aivle.backend.admin;

public enum AdminAuditAction {
    ADMIN_REAUTHENTICATION_SUCCEEDED,
    ADMIN_REAUTHENTICATION_FAILED,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    USER_SESSION_REVOKED,
    SERVICE_SETTING_CHANGED
}
